<div class="row">
    <div class="col-md-6">
        <h2>Cadastrar Postagem</h2>
    </div>
    <div class="col-md-6">
        <br>
        <a href="<?php echo $this->url('post/default', array('controller' => 'post')); ?>" class="btn btn-default pull-right">Voltar</a>
    </div>
</div>

<hr>

<?php
/**
 * @var $form \Zend\Form\Form
 */
$form = $this->form;

if($this->success)
    echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
if($this->error)
    echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';

$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
    ->setMessageCloseString('</div>')
    ->render($form);

$form->setAttribute('action', $this->url('post/default', array('controller' => 'post', 'action' => 'inserir')));
$form->prepare();
echo $this->form()->openTag($form);
?>

<br><br>
<div class="row">
    <div class="col-md-3">
        <?php echo $this->formRow($form->get('titulo'));?>
    </div>

    <div class="col-md-4">
        <?php echo $this->formRow($form->get('descricao'));?>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <?php echo $this->formRow($form->get('categoria_id'));?>
    </div>

    <div class="col-md-2">
        <?php echo $this->formRow($form->get('autor_id'));?>
    </div>

    <div class="col-md-2 checkbox">
        <br>
        <?php echo $this->formRow($form->get('ativo'));?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->formRow($form->get('texto'));?>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <?php echo $this->formRow($form->get('submit'));?>
    </div>
</div>

<?php
echo $this->form()->closetag();
?>