<div class="row">
    <div class="col-md-6">
        <h2>Index Autores</h2>
    </div>
    <div class="col-md-6">
        <br>
        <a href="<?php echo $this->url('autor/default', array('controller' => 'autor', 'action' => 'inserir')); ?>"
           class="btn btn-default pull-right">Cadastrar Autor</a>
    </div>
</div>

<hr>

<?php
if($this->success)
    echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
if($this->error)
    echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
?>

<table class="table table-hover">
    <thead>
    <tr>
        <th>#Id</th>
        <th>#Nome</th>
        <th>#Email</th>
        <th>#Ações</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /**
     * @var $entity Autor\Entity\Autor
     */
    ?>
    <?php if ($this->data): ?>
        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getId(); ?></td>
                <td><?php echo $entity->getNome(); ?></td>
                <td><?php echo $entity->getEmail(); ?></td>
                <td>
                    <a href="<?php echo $this->url('autor/default', array('controller' => 'autor', 'action' => 'editar', 'id' => $entity->getId())); ?>"
                       class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="<?php echo $this->url('autor/default', array('controller' => 'autor', 'action' => 'excluir', 'id' => $entity->getId())); ?>"
                       class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <p>Não há autores cadastrados!</p>
    <?php endif; ?>
    </tbody>
</table>

<?php echo  $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'autor/paginator'));?>