<h2>Home</h2>

<hr>

<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="btn-group btn-group-lg" role="group" aria-label="">
            <a class="btn btn-info" href="<?php echo $this->url('post/default', array('controller' => 'post'));?>">Cadastro de Postagens</a>

            <a class="btn btn-default" href="<?php echo $this->url('categoria/default', array('controller' => 'categoria'));?>">Cadastro de Categorias</a>

            <a class="btn btn-info" href="<?php echo $this->url('autor/default', array('controller' => 'autor'));?>">Cadastro de Autores</a>
        </div>
    </div>
</div>
