<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Mini Dash Postagens'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . ''))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/dashboard.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand title-navbar" href="<?php echo $this->url('index/default', array('controller' => 'index')); ?>">Área de Postagens</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="">
                            <a class="a-menu-lateral" href="<?php echo $this->url('index/default', array('controller' => 'index')); ?>">
                                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                                 Home
                            </a>
                        </li>
                        <li class="">
                            <a class="a-menu-lateral" href="<?php echo $this->url('post/default', array('controller' => 'post')); ?>">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                                Postagens
                            </a>
                        </li>
                        <li class="">
                            <a class="a-menu-lateral" href="<?php echo $this->url('autor/default', array('controller' => 'autor'));?>">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                Autores
                            </a>
                        </li>
                        <li class="">
                            <a class="a-menu-lateral" href="<?php echo $this->url('categoria/default', array('controller' => 'categoria')); ?>">
                                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                                Categoria
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
